# uncomment the line below and change the compiler flags if you need to (use at least c++11 on the server)
# CXXFLAGS = -std=c++11 

all: 
	g++ Phase1Main.cpp $(CXXFLAGS) -o Phase1
	g++ LazyTestMain.cpp $(CXXFLAGS) -o Lazy
	g++ RuntimeTestMain.cpp $(CXXFLAGS) -o Run
	g++ CDABreakMain.cpp $(CXXFLAGS) -o Break
main:
	g++ Phase1Main.cpp $(CXXFLAGS) -o Phase1
lazy:
	g++ LazyTestMain.cpp $(CXXFLAGS) -o Lazy
run:
	g++ RuntimeTestMain.cpp $(CXXFLAGS) -o Run
break:
	g++ CDABreakMain.cpp $(CXXFLAGS) -o Break
